displayName: Tenant Redirect
type: middleware

import: github.com/ndeitch/traefik-tenant-plugin

summary: "Redirect request to specific pod based on header matching values fetched from all pods endpoint"

# Following config will redirect requests to the pod that returned "x-tenant-id" header value on /v1/tenants endpoint
testData:
  enabled: true
  header: "x-tenant-id"
  serviceName: "products"
  dataSourceURL: "/v1/tenants"
